name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: worm
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build Plugin
      run: mvn -B package --file pom.xml

    - name: Publish to RabbitHole Maven
      run: mvn --batch-mode deploy
      env:
          MAVEN_USERNAME: ${{ secrets.GUMPREPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GUMPREPO_TOKEN }}
